spring:
  application:
    name: order
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://10.249.0.25:3307/SpringCloud_Sell?useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
